# Generated by Django 4.2.29 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_payment_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
